package(
    default_visibility = ["//src:__subpackages__"],
)

java_binary(
    name = "directory_manifest",
    srcs = [
        "App.java"
    ],
    main_class = "io.github.hcoona.directory_manifest.App"
)
